### PR TITLE
tighten spacing above how it works

### PR DESCRIPTION
**Pull request by jgallen23**
screenshot 2017-01-30 at 3 53 28 pm

cc @daybowbow

### CODE REVIEW

**Comment by blake213** [comment]
I feel like the spacing of the form in the hero is too tight now. I understand the desire to have things above the fold, however research shows that "below the fold" actually doesn't matter as much as it once did -- users tend to scroll down, especially on mobile devices.

Secondly, the placement of the like button in the top navigation is lost in the blue background, and it makes the page feel unbalanced. That's why in my version I put it below the introduction paragraph.

Unless anyone has any major objections, I would like to at least revert the change of the like button positioning to below the introduction paragraph.

**Comment by daybowbow** [comment]
@blake213  - messaging you via Slack about this as well.

Checked with the team today on this and business requirements are to keep the Share buttons at the top - don't love them there either but can't move them back down. As a happier medium, we will add context copy (issue [here](https://github.com/technologists-for-progress/callsforchange/issues/98)). Also in there is to add a little more padding below the buttons so it's not so tight (per your comments) against the form.

We'll make the intro paragraph copy black and a little larger as well - so once that text moves down it'll fill the space better. But I do think we should tighten up the spacing above How it Works (per this original ticket) - what's your recommendation there?

**Comment by daybowbow** [comment]
@jgallen23 @blake213 made updates tonight that address this Issue (https://github.com/technologists-for-progress/callsforchange/pull/99) so we can close this.

**Comment by jontg** [comment]
Closing as per comments.

**Pull request closed without merging**
